### ISSUE TITLE
The system crashes for a couple of seconds.

### ISSUE THREAD

**Issue by htobon** [CCAFS/DM-Support#1]
The system crashes for a couple of seconds if the user change between one option to another.

I have identified that this crash cause the mouse stop moving.

It would be great to have a loading icon while the system looks into the database to get the list of files.

**Comment by sebas932** [comment]
This issue was resolved on commit fb5c6140aef8e55d39ff11ef8d3c6573f52d1216, this happened due to an error in the AJAX implementation.
