### ISSUE TITLE
Rename database prefix.

### ISSUE THREAD

**Issue by htobon** [CCAFS/DM-Support#3]
Since the system is integrated with Drupal, it would be great to differentiate between the tables that belong to the CMS and the tables that belong to the system.

My recommendation would be to let the current DMSP Tables as they are right now, and to rename the CMS' tables.

**Comment by sebas932** [comment]
Renamed and adapted code to change PREFIX easily d14d3654906cf50dc340c0f86723b30f64f94a86

![image](https://f.cloud.github.com/assets/4406128/1694971/87fe287c-5eaa-11e3-83c5-9a86f5b73a4b.png)

**Comment by htobon** [comment]
Excellent.
